% =========================================================================
% OHWTBPerf 1.02 BY CHIZHI                                   [OHWTBAnsys.m]
% -------------------------------------------------------------------------

function [] = OHWTBAnsys(main_dir,r,wind_speed,iter_Vw,FX_data,...
    FY_data,M14_data,tip_loss_model,hub_loss_model,brake_state_model)

r_element = r;

Ansys_dir = [main_dir,'Results\AnsysLoad\Loads_',num2str(tip_loss_model),'_',num2str(hub_loss_model),'_',num2str(brake_state_model),'\'];

if ~exist(Ansys_dir, 'dir')
    % Folder does not exist so create it.
    mkdir(Ansys_dir);
end

delete([Ansys_dir,'*.txt']);

for k = 1 : iter_Vw
    
    Ansys_file = [Ansys_dir,'Load_0',num2str(wind_speed(k)),'.txt'];
    fid_Ansys = fopen(Ansys_file,'w');
    
    fprintf(fid_Ansys,'/PREP7\n');
  
    fprintf(fid_Ansys,sprintf('! Date/Time: %s\n',datestr(clock)));
    fprintf(fid_Ansys,'! Generated by: OHWTBPerf v1.02\n');
    fprintf(fid_Ansys,'! 5 MW NREL blade\n');
    fprintf(fid_Ansys,sprintf('! A set of loads at wind speed: %4.1f m/s\n',wind_speed(k)));
    fprintf(fid_Ansys,'*get,var1,node,0,num,max\n');

    
    
    for i = 1 : length(r_element)
        
        fprintf(fid_Ansys,'node_%i = node(0,0,%4.2f)\n',i,r_element(i));
        
    end
    
    i = 0;
    
    for j = length(r_element) : -1 : 1
        
        i = i+1;
        fprintf(fid_Ansys,sprintf...
            ('\n! {Loads at r = %4.2f m measured from root flange}\n',...
            r_element(j)));
        fprintf(fid_Ansys,sprintf('F,node_%i,FX,%8.2f\t! [N]\n',i,...
            FX_data(j,k)));
        fprintf(fid_Ansys,sprintf('F,node_%i,FY,%8.2f\t! [N]\n',i,...
            FY_data(j,k)));
        fprintf(fid_Ansys,sprintf('F,node_%i,MZ,%8.3f\t! [N-m]\n',i,...
            M14_data(j,k)));
        
    end
    fprintf(fid_Ansys,'FINISH\n');
    fprintf(fid_Ansys,'/SOL\n');
    fprintf(fid_Ansys,'!*\n');
    fprintf(fid_Ansys,'ANTYPE,0\n');
    fprintf(fid_Ansys,'!*\n');
    fprintf(fid_Ansys,'CNVTOL,U,,0.05,2,,\n');
    fprintf(fid_Ansys,'!*\n');
    fprintf(fid_Ansys,'DELTIM,100,100,10000\n');
    fprintf(fid_Ansys,'OUTRES,ERASE\n');
    fprintf(fid_Ansys,'OUTRES,ALL,ALL\n');
    fprintf(fid_Ansys,'NCNV,0,0,0,0,0\n');
    fprintf(fid_Ansys,'RESCONTRL,DEFINE,ALL,ALL,0\n');
    fprintf(fid_Ansys,'/STATUS,SOLU\n');
    fprintf(fid_Ansys,'SOLVE\n');
    fprintf(fid_Ansys,'FINISH\n');
    fprintf(fid_Ansys,'/POST1\n');
    fprintf(fid_Ansys,'!*\n');
    fprintf(fid_Ansys,'/EFACET,1\n');
    fprintf(fid_Ansys,'PLNSOL,S,EQV, 0,1.0\n');
%     fprintf(fid_Ansys,'PLNSOL,U,Y, 0,1.0\n');
    fprintf(fid_Ansys,'/plopts,date,0\n');
    
    fclose('all');
    
end
Ansys=1;


%==========================================================================
